#!/bin/bash

## Find and fix broken images and links caused by how the baseURL is set in the config.yml
find docs/public -type f -name "*.html" -exec sed -i 's/="\/\//="\//g' {} \;

mv docs/public nginx-ingress-controller
mkdir -p docs/public
mv nginx-ingress-controller docs/public
mv docs/public/nginx-ingress-controller/_cloudcannon docs/public